name: Go
permissions:
  contents: read
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:

  build:
    strategy:
      matrix:
        go-version: ['stable', 'oldstable']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
    - name: Install Go
      if: success()
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
        cache: true

    - name: Run tests
      run: |
        go test -v ./...
        go test -race -v ./...
        go vet ./...

    - name: Check mod tidy
      run: |
        go mod tidy
        git diff --exit-code go.mod go.sum
